# -*- coding: utf-8 -*-
"""examen

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_ophiSFC9AZ3PEFtpBO7Ire3e2vrmoL
"""

import math
import os
import random
import re
import sys

numeroInteligente = 0

numero = int(input("Numero que desea probar: "))
contador = 0
lista = []
if numero < 0:
  print("Digite un numero")
for NumeroI in range(1,numero+1):
    if (numero % NumeroI) == 0 :
        contador += 1
        lista.append(NumeroI)
print(lista)
if len(lista) > 2:
  print("el numero",numero,"si es inteligente")
elif len(lista) <= 2:
    print("el numero",numero,"no es inteligente")

